### ISSUE TITLE
Use of dev_sig

### ISSUE THREAD

**Issue by siddhantkhandelwal** [bitsacm/sig_tracker#10]
The Readme file does not explain the requirement of two apps, 'about_sig' and 'dev_sig'. Can't we merge those two apps into one, say, 'main'?

**Comment by apb7** [comment]
Hi @siddhantkhandelwal, can you please provide more context here?
Also, adding @sharifa2708 to explain why we require those two separate apps.

**Comment by siddhantkhandelwal** [comment]
What I can infer here is that this app is for the moderators of the SIGs. I don't think we need separate app for admin tasks. These can be accomplished using the Django Admin Interface. Developing a custom interface would be redundant. Rather, we should customise the Django Admin Interface according to our requirements.

**Comment by apb7** [comment]
Oh, I think you're getting it a bit wrong. `dev_sig` is the app for development SIG and so on and so forth.

**Comment by apb7** [comment]
Also, there are no URLs mapping for `dev_sig`, that is, `/dev_sig/` throws an error.
@sharifa2708 you may want to fix this?

**Comment by siddhantkhandelwal** [comment]
Well, having separate apps for each SIG is not a very good idea. I think we need to merge these apps into one.

**Comment by apb7** [comment]
I agree with you. Let us plan this up in the group and then make changes accordingly so that everyone knows what has been decided.

**Comment by siddhantkhandelwal** [comment]
Yeah, let's do this!

**Comment by sharifa2708** [comment]
I was thinking of making 3 different individual apps for the 3 sigs as it would include a feedback mechanism for the sigs and then customising the admin interface accordingly. Or we can even drop this option of 3 different apps for sigs and make a separate app for feedback for individual sigs.

**Comment by siddhantkhandelwal** [comment]
I hope we talk about this soon enough. We don't have much time.
